### YamlMime 
# Pipeline that builds and deploys componenten.

name: $(BuildDefinitionName)_$(GitVersion_SemVer)

trigger:
  batch: 'true'
  tags:
    include:
      - '*'
  branches:
    include: 
      - master

resources:
  repositories:
  - repository: PGGM.PipelineTemplates
    name: PGGM/PGGM.Web.Components.Pipeline
    type: git
    ref: 'refs/heads/master'

# for mijnpfzw use this
extends:
  # template: deployments/templates/pfzw-build-and-deploy-to-azure.yml@PGGM.PipelineTemplates
  template: deployments/templates/1.0.0.2/pfzw-build-and-deploy-to-azure.yml@PGGM.PipelineTemplates
  parameters:
    installChrome: false
# for werkgevers use this
#stages:
#  - template: deployments/templates/build-stage.yml@PGGM.PipelineTemplates

